### PR TITLE
add Portuguese (Brazilian) translation

### PR DESCRIPTION
**Pull request by thiagowfx**
Hi,

I just created a translation for the Portuguese (Brazilian) language.

### CODE REVIEW

**Comment by pbrisbin** [comment]
Hi thanks! I doubt this is causing the build failure but I'd like to get that addressed before merging any PRs. Will bring this in as soon as I do.

**Comment by pbrisbin** [comment]
I think I addressed the build issue. Can you try rebasing this over current master?

**Comment by thiagowfx** [comment]
Sure. I did a 

    git rebase upstream/master

from the br branch, where upstream is your repo. However, when I try to do a

    git push origin br

my push is rejected. I understand why, it is because the branch history was modified (with the rebase).

I belive this scenario is quite standard with PRs, but I'm not used to it. Would force pushing the br branch to origin break this pull request? Is this the right procedure?

**Comment by pbrisbin** [comment]
Yeah that's exactly right. It's generally fine to rewrite history on branches to clean things up or ensure a fast-forward merge can be done -- as long as you don't rewrite a published branch that others may have pulled. Usually this means it's OK to rebase/force-push a PR, but never master.

```
git push -f origin br
```

**Comment by thiagowfx** [comment]
Nice, thanks for the explanation. I just did it.

**Comment by pbrisbin** [comment]
Awesome, and a green build. Thanks again!

**Pull request merged**
