### PR TITLE
Ignore prompt default option clarification

### PR DESCRIPTION
**Pull request by atreyasha**
Pull request to merge changes from #127 along with locale updates.

### CODE REVIEW

**Comment by atreyasha** [comment]
@pbrisbin: merged this change. I would say we could now do a minor version bump because of several changes since the last release (https://github.com/pbrisbin/downgrade/compare/v8.0.0...master).

**Comment by pbrisbin** [comment]
I don't see any new functionality there, it seems mostly internal stuff and minor copy changes, so I'm inclined to go with only a patch bump, 8.0.1 -- WDYT?

**Comment by atreyasha** [comment]
Yes, while most of the diffs are indeed patch-worthy, I would argue commit e30e90c involves a behaviour change since the additional `-L` flag prepended to `find` would now allow for `find` to search through symlinks; whereas this was not possible earlier. This is why I think am inclined to a minor version bump. WDYT?

**Comment by pbrisbin** [comment]
Eh, I can't decide if that is a Bugfix or a Feature. But I don't feel strongly, so 8.1.0 it is.

**Pull request merged**
