### PR TITLE
Add `==` as a version operator alias of `=`

### PR DESCRIPTION
**Pull request by atreyasha**
### Checklist

- [x] No duplicate issues/PRs
- [x] Update usage function
- [x] Update unit tests
- [x] Update shell completions
- [x] Update mandoc
- [x] Update readme
- [x] Update locales
- [x] Update change log, if releasing

### Description

This PR adds the `==` version operator as an alias of the already existing `=` operator. The reason why I added the `=` operator in the first place was to be consistent with the version comparison style in `pacman`. But then I realized that that some users might be more familiar with using `==` instead, so why not have them both?

**PS:** Let's release after this PR, I think we have enough new stuff for a minor version bump. Then I can move on to #118 and #158 after.

### CODE REVIEW

**Comment by atreyasha** [comment]
Miscellaneous changes:

1. I found that the path of our new configuration file was wrong in the readme and mandoc, so I fixed these.
2. The changelog's `Ongoing` entry compared against the legacy `master` branch, so I fixed this to `main`.

**Review by pbrisbin — APPROVED** [review]

**Comment by atreyasha** [comment]
@pbrisbin BTW could you allow me to have write access to `main`?

Our previous change to `Makefile` involves a final commit to `main` which updates the `DOWNGRADE_VERSION` variable inside `downgrade`, and I am currently not able to do this without write-access.

**Comment by pbrisbin** [comment]
I don't think it's actually permissions (well not directly) that is blocking your push to `main`; I think it's branch protection, which requires status checks (and so a PR) for any non-admin pushing to that branch. I also can't seem to find anyway to make you an admin of this repository (we'd have to make an organization and move the repository to do that).

I'm happy to explore the organization approach, but in the meantime why can't we do the version change in a PR?

**Comment by atreyasha** [comment]
> but in the meantime why can't we do the version change in a PR?

That's possible as well, just more repetition of things that can automated. Will open one now.

**Comment by pbrisbin** [comment]
> more repetition of things that can automated

On that topic, we should definitely look into GitHub Actions. I've been moving all my repositories to it, and it's easier to automate release activities there than Circle. I'll open an Issue and start discussing options.

**Pull request merged**
