### PR TITLE
Bugfix for `sed` error messages

### PR DESCRIPTION
**Pull request by atreyasha**
### Checklist

* Admin:
  - [x] No duplicate PRs
* Integration:
  - [x] Update unit tests
  - [x] Update shell completions
  - [x] Update configuration file
* Documentation:
  - [x] Update usage function
  - [x] Update mandoc
  - [x] Update readme
  - [x] Update locales
* Release:
  - [x] Update change log
  - [x] Update `DOWNGRADE_VERSION`

### Description

This PR addresses #184 by directing `stderr` from all `sed` commands to `/dev/null`.

I considered wrapping the blocks/pipes  where `sed` is used with an if-statement that checks for their exit codes as per https://github.com/pbrisbin/downgrade/issues/184#issuecomment-1053652095. But given there are several such blocks with `sed`, I thought it might be simpler to just direct the error message to `/dev/null`. The downside is that we don't get a special error message specifying invalid input, but we would still get the `No results found` error message which is not incorrect either.

WDYT?

### CODE REVIEW

**Review by pbrisbin — COMMENTED** [review]
I guess I'm just not clear on the behavior we're trying to fix.

If the behavior is

```console
% downgrade whatever
sed error...
[exit 1]
```

Then I don't like this fix. It'll just remove output and add nothing useful.

I think you're suggesting the current behavior is:

```console
% downgrade whatever
sed error...
No results found
[exit 1]
```

In which case, I can see the reasoning to just silence it.

However, my suggestion for silencing that sed error was built on the assumption that it was the only (-ish) one that led to the no-results outcome. Silencing a dozen `sed` errors seems like a recipe for leaving no indication what (or if anything) went wrong in a no-results case.

I think we have to look the `sed`s individually. If a given `sed` will "only" (with reasonable confidence) fail because the user's search term was invalid, then silencing it and letting "No results found" show is reasonable. Ideally, you'd see "invalid search", but I can get behind the simplification that an invalid search leads to no results.

But many (most?) of these `sed` lines are (e.g.) reading `pacman.conf`, parsing a package path, etc. Failures here would (probably?) be coding errors on our part. A blanket "No results found" is a bit of a problem.

So I would suggest that we only change the `sed` that we know failed in that bug report, the one that we know fails because of an invalid search term. I think that would be the most minimal bugfix and a net improvement.

As more comprehensive alternative, we could introduce something like this:

```sh
sed_msg() {
  local msg=$1
  shift

  if ! sed "$@"; then
    echo "Failed $msg" >&2
    exit 1
  fi
}
```

And then,

```diff
-sed -i "$ln s/.*/&\\nIgnorePkg = $pkg/" "$PACMAN_CONF"
+sed_msg "adding IgnorePkg" -i "$ln s/.*/&\\nIgnorePkg = $pkg/" "$PACMAN_CONF"
```

Or something...

**Comment by atreyasha** [comment]
> I guess I'm just not clear on the behavior we're trying to fix.
> I think you're suggesting the current behavior is:
>
> ```
> % downgrade whatever
> sed error...
> No results found
> [exit 1]
> ```

Exactly, this is the current behaviour and I would like to ideally silence the `sed` error messages in such cases.

> So I would suggest that we only change the sed that we know failed in that bug report, the one that we know fails because of an invalid search term. I think that would be the most minimal bugfix and a net improvement.

True. I looked deeper and found that the `sed` errors arise from the `process_term` function:

https://github.com/pbrisbin/downgrade/blob/4c3af2cfee79f2c4265abe69961fa1cc2dca2f4b/downgrade#L322-L326

Somehow despite the inner `sed` commands from `process_term` returning exit-code 1, the `process_term` function still continues to completion. This stops when I remove the if-block around `process_term`.

> As more comprehensive alternative, we could introduce something like this:
> ```shell
> sed_msg() {
>  local msg=$1
>  shift
>
>  if ! sed "$@"; then
>    echo "Failed $msg" >&2
>    exit 1
>  fi
> }
> ```

Works like a charm. Modified the PR.

WDYT?

**Review by pbrisbin — APPROVED** [review]
Should we add a test case?

**Comment by atreyasha** [comment]
Yes, done

**Pull request merged**
